### ISSUE TITLE
Separation of Concern/Duplication in Dot Vision

### ISSUE THREAD

**Issue by Agung-Krisna** [alvinwatner/dot-vision#3]
Currently there is dot_vision_stream and dot_vision which holds the same functionality, just different implementation of display method. 

Further release may merge these two files, and giving a choice for the display method through `--display (cv2 | web)` in the program.

**Comment by alvinwatner** [comment]
Sounds good to me

**Comment by alvinwatner** [comment]
Hello @Agung-Krisna I have made a PR for this issue.
